package com.sample

import java.util.List;
import com.sample.DecisionEngineInputMessage;

function String setDecision(List risks){
	int j = 1;
	String result = "";
	for(int i = 0; i<risks.size(); i++){
		if ((Integer)risks.get(i) > j)
			j = (Integer)risks.get(i);
	}
	if (j == 3)
		result = "reject";
	else if(j == 2)
		result = "review";
	else if(j == 1)
		result = "accept";
	return result;
}

rule "POLICYRULEDECISION"
ruleflow-group "PolicyRuleDecision"
lock-on-active true
// 设定政策规则最终结果
	when
		$model : DecisionEngineInputMessage(m: policyRuleResult)
   	then
   		$model.setPolicyRuleDecision(setDecision(m));
end

